version: "3.0"

services:
  l4d2:
    build: .
    restart: unless-stopped
    env_file: .env
    environment:
      - HOSTNAME=${HOSTNAME}
      - REGION=4
      - STEAM_GROUP=${STEAMGROUP}
      - DEFAULT_MAP=c1m1_hotel
    ports:
      - "27015:27015/tcp"
      - "27015:27015/udp"
    volumes:
      - ./addons:/addons
      # Sourcemod Config
      - ./cfg/sourcemod/sourcemod.cfg:/cfg/sourcemod/sourcemod.cfg
      - ./cfg/sourcemod/sm_warmode_on.cfg:/cfg/sourcemod/sm_warmode_on.cfg
      - ./cfg/sourcemod/sm_warmode_off.cfg:/cfg/sourcemod/sm_warmode_off.cfg
      # Server Config
      - ./cfg/server.cfg:/cfg/server.cfg
      - ./cfg/server_rates.cfg:/cfg/server_rates.cfg
    #network_mode: host
