version: "3.0"

services:
  l4d2:
    build: .
    restart: unless-stopped
    env_file: .env
    environment:
      - HOSTNAME=${HOSTNAME}
      - REGION=4
      - STEAM_GROUP=${STEAMGROUP}
      - DEFAULT_MAP=c1m1_hotel
    ports:
      - "27015:27015/tcp"
      - "27015:27015/udp"
    volumes:
      - ./addons:/addons
      # Sourcemod
      - ./cfg/sourcemod/sourcemod.cfg:/cfg/sourcemod/sourcemod.cfg
      # Server Config
      - ./cfg/server.cfg:/cfg/server.cfg
      - ./cfg/server_rates.cfg:/cfg/server_rates.cfg
      # Multislots
      - ./cfg/sourcemod/l4dmultislots.cfg:/cfg/sourcemod/l4dmultislots.cfg
      - ./cfg/sourcemod/l4d2_character_manager.cfg:/cfg/sourcemod/l4d2_character_manager.cfg
#network_mode: host
networks:
  backend:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1280
