version: "3.0"

services:
  l4d2:
    build: .
    restart: unless-stopped
    env_file: .env
    environment:
      - HOSTNAME=${HOSTNAME}
      - REGION=4
      - STEAM_GROUP=${STEAMGROUP}
      - STEAM_GROUP_EXCLUSIVE=false
      - DEFAULT_MAP=c1m1_hotel
    ports:
      - "27015:27015/tcp"
      - "27015:27015/udp"
    volumes:
      - ./addons:/addons
      # Load All Config
      - ./cfg:/cfg
#network_mode: host
networks:
  backend:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1280
